import { ArrowLeft, Bot, Clock3, FileWarning, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { scopedPath, useApi } from '../api'
import { ArtifactId } from '../components/ArtifactId'
import { DataState } from '../components/StateView'
import { StatusPill } from '../components/StatusPill'
import { useScope } from '../scope'
import type { CaseFile } from '../types'

export function CaseFilePage() {
  const { scopeId } = useScope()
  const { caseId = '' } = useParams()
  const state = useApi<CaseFile>(scopedPath(scopeId, `/cases/${encodeURIComponent(caseId)}`))
  return <section className="page-stack"><Link className="back-link" to={`/exceptions?scope=${encodeURIComponent(scopeId)}`}><ArrowLeft size={15} />Exception queue</Link><DataState state={state}>{(file) => <>
    <div className="case-header"><div><span className="eyebrow">Case File</span><h1>{file.case.affected_amount.display}</h1><div className="id-line"><ArtifactId value={file.case.case_id} /><ArtifactId value={file.case.settlement_id} /></div></div><div className="case-status-stack"><StatusPill status={file.case.financial_status} /><StatusPill status={file.case.workflow_status} /></div></div>
    <div className="case-grid"><article className="case-summary"><div className="summary-line"><Clock3 size={16} /><span>First seen</span><strong>{new Date(file.case.first_seen_at).toLocaleString()}</strong></div><div className="summary-line"><UserRound size={16} /><span>Owner</span><strong>{file.case.owner ?? 'Unassigned'}</strong></div><div className="summary-line"><FileWarning size={16} /><span>Blocker</span><strong>{file.case.source_blockers.join(' · ') || 'None'}</strong></div><div className="summary-line"><span className="fingerprint-dot" /><span>Fingerprint</span><ArtifactId value={file.case.incident_fingerprint_id} /></div></article>
      <article className="investigation-panel"><div className="fragment-title"><Bot size={18} /><div><strong>Bounded investigator</strong><span>Advisory only · Gate 16</span></div>{file.investigation && <StatusPill status={file.investigation.status} />}</div>{file.investigation ? <><div className="agent-action">{file.investigation.next_action}</div><p>{file.investigation.hypothesis ?? file.investigation.rejection_reason ?? 'No hypothesis returned.'}</p><div className="agent-meta"><span>{file.investigation.trace_count} tool traces</span>{file.investigation.request_source_kind && <span>Requests: {file.investigation.request_source_kind}</span>}</div><ArtifactId value={file.investigation.investigation_id} /></> : <p className="quiet">No investigation artifact is bound to the latest case/proof version.</p>}</article></div>
    <section><div className="section-heading"><div><span className="eyebrow">Evidence chronology</span><h2>What changed, and when?</h2></div></div><div className="timeline">{file.observations.map((observation) => <div className="timeline-item" key={observation.observation_id}><span className="timeline-dot" /><div><div className="timeline-title"><strong>Proof observation</strong><StatusPill status={observation.financial_status} /></div><p>{observation.reason_codes.join(' · ') || 'No failure reasons.'}</p><div className="source-state-inline">{observation.source_states.map((source) => <span key={source.manifest_id}>{source.source_kind}: <b>{source.completeness}</b>{source.received_late ? ' · late' : ''}</span>)}</div><ArtifactId value={observation.observation_id} /><small>{new Date(observation.observed_at).toLocaleString()}</small></div></div>)}{file.dispositions.map((disposition) => <div className="timeline-item disposition-item" key={disposition.disposition_id}><span className="timeline-dot" /><div><div className="timeline-title"><strong>Operator disposition · {disposition.kind.replaceAll('_', ' ')}</strong></div><p>{disposition.note ?? 'No note.'}</p><small>{disposition.actor_id} · {new Date(disposition.occurred_at).toLocaleString()}</small></div></div>)}</div></section>
    <section className="case-proof-link"><div><span className="eyebrow">Current proof</span><strong>{file.proof.composition.settlement_amount.display}</strong><StatusPill status={file.proof.status} /></div><Link className="inline-link" to={`/proofs/${encodeURIComponent(file.proof.proof_id)}?scope=${encodeURIComponent(scopeId)}`}>Inspect exact proof →</Link></section>
  </>}</DataState></section>
}
